# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-15 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='data_reviewed',
        ),
        migrations.AddField(
            model_name='book',
            name='date_reviewed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
